name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Install strace
            run: sudo apt-get update && sudo apt-get install -y strace
          - name: Run full test with strace
            run: strace -f ./full-test.sh
    debug-finder-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: 'recursive' # Ensures submodules are checked out

        - name: Create dummy conf files
          run: |
            mkdir -p conf
            echo "assignment1" > conf/assignment.txt
            echo "testuser" > conf/username.txt
            # Also need the parent conf file for the script to work
            mkdir -p ../conf
            cp conf/assignment.txt ../conf/assignment.txt

        - name: Run finder-test.sh directly
          run: |
            cd finder-app
            ./finder-test.sh
